repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
        types_or: [ python, pyi]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
    - id: shellcheck

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer

  -   repo: https://github.com/pre-commit/sync-pre-commit-deps
      rev: v0.0.3
      hooks:
      -   id: sync-pre-commit-deps

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        name: Run black on docs
        args:
          - --line-length=110
          - --target-version=py310
          - --target-version=py311
          - --target-version=py312
          - --target-version=py313
        alias: blacken-docs
        additional_dependencies: ['black==24.10.0']
